---
engine_version: 0.4.27
file_version: 2024-08-01 18:26:37.544084000 Z
resources: []
configs:
- key: header.links
  value:
  - name: Reports
    link_type: reports
  - name: Forms
    link_type: forms
  - name: "⭐ Star on GitHub"
    path: https://github.com/motor-admin/motor-admin-rails
  - conditions: []
    type: header
    name: Home
    path: "/home"
    link_type: header
  updated_at: 2024-08-01 18:26:37.544084000 +00:00
queries: []
dashboards: []
forms: []
alerts: []
api_configs:
- id: 1
  name: origin
  url: "/"
  preferences: {}
  description: 
  updated_at: 2024-08-01 17:51:28.150381000 +00:00
